# Generated by Django 4.2.7 on 2023-11-04 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('FC', 'Fiction'), ('NFC', 'Non_Fiction'), ('JN', 'Fantasy'), ('MS', 'Mystery'), ('SFC', 'Science_Fiction')], max_length=5),
        ),
    ]
